name: Clean Workflow

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 */7 * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.REPO_TOKEN }}
          retain_days: 7