name: Fix Errors

on:
  workflow_dispatch:

  schedule:
    - cron: "30 * * * *"

jobs:
  fix-hash:
    name: Fix Errors
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Fix hash errors
      run: |
        python ./bin/fix-hash.py   
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fix errors
        skip_dirty_check: false
