on:
  schedule:
    - cron: 0 * * * *

name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@stable
      env:
        GITH_EMAIL: 37431235+Apocalypsor@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SKIP_UPDATED: '1'
