name: Update Bucket

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Excavate
      uses: shovel-org/GithubActions@main
      env:
        GITH_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SKIP_UPDATED: '1'
